/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.HashMap;

/**
 *
 * @author USER
 */
public class frmRepSuppParam extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRepSuppParam
     */
    public frmRepSuppParam() {
        initComponents();
        cargarPaises();
    }
    private void cargarPaises(){
        try{
            DAO.SupplierDAO dao = new DAO.SupplierDAO();
            java.util.Vector<BEAN.Supplier> lista = dao.listaSuppliers("");
            cmbPaises.removeAllItems();
            java.util.HashSet<String> pUnicos = new java.util.HashSet<>();
            for (BEAN.Supplier sup : lista) {
                String pais = sup.getCountry();
                if (pais != null && !pais.trim().isEmpty()) {
                    pUnicos.add(pais.trim());
                }
            }
            java.util.List<String> listaOrdenada = new java.util.ArrayList<>(pUnicos);
            java.util.Collections.sort(listaOrdenada);
            
            for (String p : listaOrdenada) {
                cmbPaises.addItem(p);
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPaises = new javax.swing.JComboBox<>();
        btnReportar = new javax.swing.JButton();

        jLabel1.setText("REPORDE DE PROVEEDORES POR PAIS ");

        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(cmbPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReportar)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportar))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        try {
            if (cmbPaises.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un país.");
                return;
            }
            String paisSeleccionado = cmbPaises.getSelectedItem().toString();
            HashMap parametros = new HashMap();
            parametros.put("PaisParam", paisSeleccionado);
            String ruta = "src/REPORTS/repSuppliersParam.jasper"; 
            UTIL.dbBean db = new UTIL.dbBean();
            db.connectRep(ruta, parametros, true);
            this.dispose();
            
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnReportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportar;
    private javax.swing.JComboBox<String> cmbPaises;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
