package UI;

import UTIL.dbBean;
import java.util.HashMap;
import javax.swing.JDesktopPane;
import net.sf.jasperreports.engine.JRException;

public class frmRepProductsRango extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    
    /**
     * Creates new form frmRepProductsRango
     */
    public frmRepProductsRango(int mdiH, int mdiW, JDesktopPane desktop) {
        int slx, sly;
        initComponents();
        slx = (mdiH / 2) - (675 / 2);
        sly = (mdiW / 2) - (215 / 2);
        this.setLocation(slx, sly);
        this.desktop = desktop;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReportar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("desde");

        jLabel2.setText("Hasta");

        jLabel3.setText("REPORTE DE PRODUCTOS POR RANGO DE PRECIO UNITARIO");

        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReportar)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportar))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        double d = Double.parseDouble(this.txtdesde.getText());
        double a = Double.parseDouble(this.txtHasta.getText());
        HashMap map = new HashMap();
        map.put("parPrecMin", d);
        map.put("parPrecMax", a);
        
        String tipoRep = "Products";
        String tipo = "Param";

        FrmReporte frmReporte = new FrmReporte(tipoRep, map, tipo);
        desktop.add(frmReporte);
        frmReporte.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnReportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtdesde;
    // End of variables declaration//GEN-END:variables
}
