/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import BEAN.Supplier; 
import DAO.SupplierDAO; 
import UTIL.Util;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FrmSupplier extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    SupplierDAO supDao;
    Util util;
    public FrmSupplier(int mdiW, int mdiH) {
        initComponents();
        int slx, sly, wd = mdiW, hd = mdiH;
        
        this.setSize(1100, 600);
        slx = (mdiW/2) - (this.getWidth()/2);
        sly = (mdiH/2) -(this.getHeight()/2);
        this.setLocation(slx, sly);
        this.setResizable(false);
        this.jTabbedPane1.setSelectedIndex(0);
        
        dtm = (DefaultTableModel) this.tblSuppliers.getModel();
        supDao = new SupplierDAO();
        util = new Util();
        
        
        listar("");
        regularBotones(false);
    }
    private void listar(String texto){
        dtm.setRowCount(0); 
        try {
            
            Vector<Supplier> lista = supDao.listaSuppliers(texto); 
            for (Supplier s : lista) {
                
                Vector fila = new Vector();
                fila.addElement(s.getSupplierID()); 
                fila.addElement(s.getCompanyName());
                fila.addElement(s.getContactName());
                fila.addElement(s.getContactTitle());
                fila.addElement(s.getAddress());
                fila.addElement(s.getCity());
                fila.addElement(s.getRegion());
                fila.addElement(s.getPostalCode());
                fila.addElement(s.getCountry());
                fila.addElement(s.getPhone());
                fila.addElement(s.getFax());
                fila.addElement(s.getHomePage());
                dtm.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println("Error al listar: " + e.getMessage());
        }
    }
    private void limpiaFormulario() {
        this.txtSupplierID.setText("");
        this.txtCompanyName.setText("");
        this.txtContactName.setText("");
        this.txtContactTitle.setText("");
        this.txtAddress.setText("");
        this.txtCity.setText("");
        this.txtRegion.setText("");
        this.txtPostalCode.setText("");
        this.txtCountry.setText("");
        this.txtPhone.setText("");
        this.txtFax.setText("");
        this.txtHomePage.setText("");
        this.txtSupplierID.setEditable(false);
        regularBotones(false);
        
    }
    private void regularBotones(boolean tieneSeleccion) {
    
        this.btnActualizar.setEnabled(tieneSeleccion);
        this.btnEliminar.setEnabled(tieneSeleccion);
        this.btnInsertar.setEnabled(!tieneSeleccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtContactName = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        txtContactTitle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtHomePage = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtPostalCode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrSuppliers = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1081, 544));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 423));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("ID Proveedor");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 41, -1, -1));

        jLabel15.setText("Compañia");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 81, -1, -1));

        jLabel16.setText("Nombre de Contacto");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 121, -1, -1));

        jLabel17.setText("Telefono");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 161, -1, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 158, 202, -1));
        jPanel1.add(txtContactName, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 118, 202, -1));
        jPanel1.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 78, 202, -1));

        txtSupplierID.setEditable(false);
        txtSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 38, 202, -1));
        jPanel1.add(txtContactTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 38, 202, -1));

        jLabel18.setText("Cargo");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 41, -1, -1));

        jLabel19.setText("Direccion");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 81, -1, -1));

        jLabel20.setText("Ciudad");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 121, -1, -1));

        jLabel2.setText("Region");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 161, -1, -1));

        jLabel21.setText("Pais");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 201, -1, -1));

        jLabel22.setText("Codigo Postal");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 201, -1, -1));

        jLabel23.setText("Fax");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 241, -1, -1));

        jLabel24.setText("Pagina de inicio");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 241, -1, -1));
        jPanel1.add(txtHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 238, 202, -1));
        jPanel1.add(txtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 238, 202, -1));
        jPanel1.add(txtPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 198, 202, -1));

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        jPanel1.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 198, 202, -1));
        jPanel1.add(txtRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 158, 202, -1));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 118, 202, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 78, 202, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 331, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 331, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 331, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 331, -1, -1));

        jTabbedPane1.addTab("Mantenimiento", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrSuppliersMouseClicked(evt);
            }
        });

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Proveedor", "Compañia", "Contacto", "Cargo", "Direccion", "Ciudad", "Region", "Codigo Postal", "Pais", "Telefono", "Fax", "Pagina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
        });
        scrSuppliers.setViewportView(tblSuppliers);

        jPanel2.add(scrSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 78, 950, 290));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 890, -1));

        jLabel13.setText("Buscar:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 41, -1, -1));

        jTabbedPane1.addTab("Reporte", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 42, 980, 410));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Suppliers");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mantenimiento Proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 13, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIDActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        listar(this.txtBuscar.getText().trim());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void scrSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrSuppliersMouseClicked
        
    }//GEN-LAST:event_scrSuppliersMouseClicked

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (this.txtCompanyName.getText().trim().isEmpty() || this.txtContactName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe registrar obligatoriamente la Compañía y el Contacto");
        } else {
            Supplier sup = new Supplier();
            
            sup.setCompanyName(this.txtCompanyName.getText().trim());
            sup.setContactName(this.txtContactName.getText().trim());
            sup.setContactTitle(this.txtContactTitle.getText().trim());
            sup.setAddress(this.txtAddress.getText().trim());
            sup.setCity(this.txtCity.getText().trim());
            sup.setRegion(this.txtRegion.getText().trim());
            sup.setPostalCode(this.txtPostalCode.getText().trim());
            sup.setCountry(this.txtCountry.getText().trim());
            sup.setPhone(this.txtPhone.getText().trim());
            sup.setFax(this.txtFax.getText().trim());
            sup.setHomePage(this.txtHomePage.getText().trim());

            
            this.supDao.insertaSupplier(sup); 
            
            JOptionPane.showMessageDialog(this, "Proveedor registrado satisfactoriamente");
            
            
            this.limpiaFormulario();
            this.listar("");
            
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (this.txtSupplierID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione primero un registro de la lista para actualizar.");
            this.jTabbedPane1.setSelectedIndex(0);
            return;
        }

        if (this.txtCompanyName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la compañía no puede quedar vacío.");
            return;
        }

        Supplier sup = new Supplier();
        sup.setSupplierID(Integer.parseInt(this.txtSupplierID.getText()));
        sup.setCompanyName(this.txtCompanyName.getText().trim());
        sup.setContactName(this.txtContactName.getText().trim());
        sup.setContactTitle(this.txtContactTitle.getText().trim());
        sup.setAddress(this.txtAddress.getText().trim());
        sup.setCity(this.txtCity.getText().trim());
        sup.setRegion(this.txtRegion.getText().trim());
        sup.setPostalCode(this.txtPostalCode.getText().trim());
        sup.setCountry(this.txtCountry.getText().trim());
        sup.setPhone(this.txtPhone.getText().trim());
        sup.setFax(this.txtFax.getText().trim());
        sup.setHomePage(this.txtHomePage.getText().trim());

        this.supDao.actualizaSupplier(sup);

        JOptionPane.showMessageDialog(this, "Proveedor actualizado satisfactoriamente");
        this.limpiaFormulario();
        this.listar("");
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (this.txtSupplierID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la lista para proceder a eliminar.");
            this.jTabbedPane1.setSelectedIndex(0);
            return;
        }

        int resp = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este Proveedor?", "Alerta", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(this.txtSupplierID.getText());
            int validacion = this.supDao.eliminaSupplier(id); 
            
            if (validacion == 0) {
                JOptionPane.showMessageDialog(this, "Proveedor eliminado satisfactoriamente.");
                this.limpiaFormulario();
                this.listar("");
                
            } else if (validacion == 1) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar: Este proveedor tiene productos asociados en el inventario.", "Restricción de Integridad", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error crítico al intentar eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiaFormulario();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        int fila = tblSuppliers.getSelectedRow();
        if (fila >= 0) {
            this.txtSupplierID.setText(tblSuppliers.getValueAt(fila, 0).toString());
            this.txtCompanyName.setText(tblSuppliers.getValueAt(fila, 1).toString());
            
            this.txtContactName.setText(tblSuppliers.getValueAt(fila, 2) != null ? tblSuppliers.getValueAt(fila, 2).toString() : "");
            this.txtContactTitle.setText(tblSuppliers.getValueAt(fila, 3) != null ? tblSuppliers.getValueAt(fila, 3).toString() : "");
            this.txtAddress.setText(tblSuppliers.getValueAt(fila, 4) != null ? tblSuppliers.getValueAt(fila, 4).toString() : "");
            this.txtCity.setText(tblSuppliers.getValueAt(fila, 5) != null ? tblSuppliers.getValueAt(fila, 5).toString() : "");
            
            this.txtRegion.setText(tblSuppliers.getValueAt(fila, 6) != null ? tblSuppliers.getValueAt(fila, 6).toString() : "");
            this.txtPostalCode.setText(tblSuppliers.getValueAt(fila, 7) != null ? tblSuppliers.getValueAt(fila, 7).toString() : "");
            this.txtCountry.setText(tblSuppliers.getValueAt(fila, 8) != null ? tblSuppliers.getValueAt(fila, 8).toString() : "");
            this.txtPhone.setText(tblSuppliers.getValueAt(fila, 9) != null ? tblSuppliers.getValueAt(fila, 9).toString() : "");
            this.txtFax.setText(tblSuppliers.getValueAt(fila, 10) != null ? tblSuppliers.getValueAt(fila, 10).toString() : "");
            this.txtHomePage.setText(tblSuppliers.getValueAt(fila, 11) != null ? tblSuppliers.getValueAt(fila, 11).toString() : "");
            
            this.txtSupplierID.setEditable(false);
            
            regularBotones(true);
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrSuppliers;
    private javax.swing.JTable tblSuppliers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtContactName;
    private javax.swing.JTextField txtContactTitle;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHomePage;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtSupplierID;
    // End of variables declaration//GEN-END:variables
}
